apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: my-container
        image: komalmeshram123/ekart:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
  type: NodePort
